// src/app/admin/(app)/invites/_a5/copy.ts — T2.6.U1: the A5 words. From wireframe 09 A5/A5c where it has them
// ("Links", "New link", "General link", "Rotate", "Revoke this link",
// "Email (optional)", "Dish"); the rest is plain admin copy (Jon-only screen, no guest sees it). No AI suggestions.
export const A5 = {
  title: 'Links',
  titlePage: 'Links',
  cap: 'One link per person. The general link is for everyone else.',
  newLink: 'New link',
  general: 'General link',
  noGeneral: 'No general link yet.',
  rotate: 'Rotate',
  rotateConfirm: 'Rotate the general link? The old one stops working.',
  rotateYes: 'Rotate it',
  rotated: 'New general link made. The old one is dead.',
  personal: 'Personal links',
  empty: 'No personal links yet.',
  copyLink: 'Copy link',
  copyText: 'Copy text',
  copied: 'Copied.',
  copyFailed: 'Couldn’t copy. Select the link and copy it.',
  revoke: 'Revoke',
  revokeConfirm: (name: string) => `Revoke ${name}’s link? It stops working at once.`,
  revokeYes: 'Revoke it',
  keep: 'Keep it',
  revoked: 'Revoked',
  test: 'test',
  opens: (n: number) => (n === 1 ? '1 open' : `${n} opens`),
  notOpened: 'not opened',
  requests: (n: number) => (n === 1 ? '1 request' : `${n} requests`),
  noRequest: 'no request yet',
  dishGone: 'dish not bookable now',
  failed: 'That didn’t go through. Try again.',
  pick: 'Pick “New link” to make one.',
  // Create sheet (A5c)
  sheetTitle: 'New link',
  previewName: 'Name', // the preview's stand-in until the name box is filled
  willSee: (name: string) => `${name || 'They'} will see`,
  name: 'Name',
  nameHelp: 'As they’ll see it: “Dave.”',
  dish: 'Dish',
  noDish: 'No dish (the whole menu)',
  email: 'Email (optional)',
  emailHelp: 'Fills in their email on the form.',
  hopedFor: 'On the hoped-for list',
  save: 'Make the link',
  saving: 'Making…',
  made: (name: string) => `${name}’s link is ready.`,
  err: {
    name: 'Add their name (60 characters max).',
    bad_character: 'Only letters, numbers and spaces.',
    not_bookable: 'That dish can’t be booked now.',
    email: 'Check the email.',
  },
} as const;
